["github.com/alecthomas/template"]
  sumVersion = "v0.0.0-20190718012654-fb15b899a751"
  ["github.com/alecthomas/template".fetch]
    type = "git"
    url = "https://github.com/alecthomas/template"
    rev = "fb15b899a75114aa79cc930e33c46b577cc664b1"
    sha256 = "1vlasv4dgycydh5wx6jdcvz40zdv90zz1h7836z7lhsi2ymvii26"

["github.com/alecthomas/units"]
  sumVersion = "v0.0.0-20190717042225-c3de453c63f4"
  ["github.com/alecthomas/units".fetch]
    type = "git"
    url = "https://github.com/alecthomas/units"
    rev = "c3de453c63f4bdb4dadffab9805ec00426c505f7"
    sha256 = "0js37zlgv37y61j4a2d46jh72xm5kxmpaiw0ya9v944bjpc386my"

["github.com/beorn7/perks"]
  sumVersion = "v1.0.1"
  ["github.com/beorn7/perks".fetch]
    type = "git"
    url = "https://github.com/beorn7/perks"
    rev = "37c8de3658fcb183f997c4e13e8337516ab753e6"
    sha256 = "17n4yygjxa6p499dj3yaqzfww2g7528165cl13haj97hlx94dgl7"

["github.com/cespare/xxhash/v2"]
  sumVersion = "v2.1.0"
  ["github.com/cespare/xxhash/v2".fetch]
    type = "git"
    url = "https://github.com/cespare/xxhash"
    rev = "de209a9ffae3256185a6bb135d1a0ada7b2b5f09"
    sha256 = "12ad3z7ki9j07c4kx3ywkl6188i2afsjg7sl60wd21p6zkkpfjxq"

["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.1"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
    sha256 = "0hka6hmyvp701adzag2g26cxdj47g21x6jz4sc6jjz1mn59d474y"

["github.com/go-kit/kit"]
  sumVersion = "v0.9.0"
  ["github.com/go-kit/kit".fetch]
    type = "git"
    url = "https://github.com/go-kit/kit"
    rev = "150a65a7ec6156b4b640c1fd55f26fd3d475d656"
    sha256 = "09038mnw705h7isbjp8dzgp2i04bp5rqkmifxvwc5xkh75s00qpw"

["github.com/go-logfmt/logfmt"]
  sumVersion = "v0.4.0"
  ["github.com/go-logfmt/logfmt".fetch]
    type = "git"
    url = "https://github.com/go-logfmt/logfmt"
    rev = "07c9b44f60d7ffdfb7d8efe1ad539965737836dc"
    sha256 = "06smxc112xmixz78nyvk3b2hmc7wasf2sl5vxj1xz62kqcq9lzm9"

["github.com/go-stack/stack"]
  sumVersion = "v1.8.0"
  ["github.com/go-stack/stack".fetch]
    type = "git"
    url = "https://github.com/go-stack/stack"
    rev = "2fee6af1a9795aafbe0253a0cfbdf668e1fb8a9a"
    sha256 = "0wk25751ryyvxclyp8jdk5c3ar0cmfr8lrjb66qbg4808x66b96v"

["github.com/gogo/protobuf"]
  sumVersion = "v1.1.1"
  ["github.com/gogo/protobuf".fetch]
    type = "git"
    url = "https://github.com/gogo/protobuf"
    rev = "636bf0302bc95575d69441b25a2603156ffdddf1"
    sha256 = "1525pq7r6h3s8dncvq8gxi893p2nq8dxpzvq0nfl5b4p6mq0v1c2"

["github.com/golang/protobuf"]
  sumVersion = "v1.3.2"
  ["github.com/golang/protobuf".fetch]
    type = "git"
    url = "https://github.com/golang/protobuf"
    rev = "6c65a5562fc06764971b7c5d05c76c75e84bdbf7"
    sha256 = "1k1wb4zr0qbwgpvz9q5ws9zhlal8hq7dmq62pwxxriksayl6hzym"

["github.com/google/go-cmp"]
  sumVersion = "v0.3.0"
  ["github.com/google/go-cmp".fetch]
    type = "git"
    url = "https://github.com/google/go-cmp"
    rev = "6f77996f0c42f7b84e5a2b252227263f93432e9b"
    sha256 = "1hyxx3434zshl2m9ja78gwlkg1rx9yl6diqa7dnjb31xz5x4gbjj"

["github.com/google/gofuzz"]
  sumVersion = "v1.0.0"
  ["github.com/google/gofuzz".fetch]
    type = "git"
    url = "https://github.com/google/gofuzz"
    rev = "f140a6486e521aad38f5917de355cbf147cc0496"
    sha256 = "0qz439qvccm91w0mmjz4fqgx48clxdwagkvvx89cr43q1d4iry36"

["github.com/google/uuid"]
  sumVersion = "v1.1.1"
  ["github.com/google/uuid".fetch]
    type = "git"
    url = "https://github.com/google/uuid"
    rev = "0cd6bf5da1e1c83f8b45653022c74f71af0538a4"
    sha256 = "0hfxcf9frkb57k6q0rdkrmnfs78ms21r1qfk9fhlqga2yh5xg8zb"

["github.com/json-iterator/go"]
  sumVersion = "v1.1.7"
  ["github.com/json-iterator/go".fetch]
    type = "git"
    url = "https://github.com/json-iterator/go"
    rev = "27518f6661eba504be5a7a9a9f6d9460d892ade3"
    sha256 = "0n79p4s67zl5zprxv7diayw3vavnmmfqkmd6snz0i9bxp825dsyz"

["github.com/julienschmidt/httprouter"]
  sumVersion = "v1.2.0"
  ["github.com/julienschmidt/httprouter".fetch]
    type = "git"
    url = "https://github.com/julienschmidt/httprouter"
    rev = "348b672cd90d8190f8240323e372ecd1e66b59dc"
    sha256 = "1k8bylc9s4vpvf5xhqh9h246dl1snxrzzz0614zz88cdh8yzs666"

["github.com/konsorten/go-windows-terminal-sequences"]
  sumVersion = "v1.0.1"
  ["github.com/konsorten/go-windows-terminal-sequences".fetch]
    type = "git"
    url = "https://github.com/konsorten/go-windows-terminal-sequences"
    rev = "5c8c8bd35d3832f5d134ae1e1e375b69a4d25242"
    sha256 = "1lchgf27n276vma6iyxa0v1xds68n2g8lih5lavqnx5x6q5pw2ip"

["github.com/kr/logfmt"]
  sumVersion = "v0.0.0-20140226030751-b84e30acd515"
  ["github.com/kr/logfmt".fetch]
    type = "git"
    url = "https://github.com/kr/logfmt"
    rev = "b84e30acd515aadc4b783ad4ff83aff3299bdfe0"
    sha256 = "02ldzxgznrfdzvghfraslhgp19la1fczcbzh7wm2zdc6lmpd1qq9"

["github.com/leanovate/gopter"]
  sumVersion = "v0.2.4"
  ["github.com/leanovate/gopter".fetch]
    type = "git"
    url = "https://github.com/leanovate/gopter"
    rev = "c8df375e1ea5a53748eb0dff007e9cc5e07b7cd3"
    sha256 = "0i6lvrihicgxlqwc9p7aslczl47r1m7napq5jip4mlf9bq97lm3a"

["github.com/matttproud/golang_protobuf_extensions"]
  sumVersion = "v1.0.1"
  ["github.com/matttproud/golang_protobuf_extensions".fetch]
    type = "git"
    url = "https://github.com/matttproud/golang_protobuf_extensions"
    rev = "c12348ce28de40eed0136aa2b644d0ee0650e56c"
    sha256 = "1d0c1isd2lk9pnfq2nk0aih356j30k3h1gi2w0ixsivi5csl7jya"

["github.com/modern-go/concurrent"]
  sumVersion = "v0.0.0-20180306012644-bacd9c7ef1dd"
  ["github.com/modern-go/concurrent".fetch]
    type = "git"
    url = "https://github.com/modern-go/concurrent"
    rev = "bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94"
    sha256 = "0s0fxccsyb8icjmiym5k7prcqx36hvgdwl588y0491gi18k5i4zs"

["github.com/modern-go/reflect2"]
  sumVersion = "v1.0.1"
  ["github.com/modern-go/reflect2".fetch]
    type = "git"
    url = "https://github.com/modern-go/reflect2"
    rev = "94122c33edd36123c84d5368cfb2b69df93a0ec8"
    sha256 = "06a3sablw53n1dqqbr2f53jyksbxdmmk8axaas4yvnhyfi55k4lf"

["github.com/mwitkow/go-conntrack"]
  sumVersion = "v0.0.0-20161129095857-cc309e4a2223"
  ["github.com/mwitkow/go-conntrack".fetch]
    type = "git"
    url = "https://github.com/mwitkow/go-conntrack"
    rev = "cc309e4a22231782e8893f3c35ced0967807a33e"
    sha256 = "0nbrnpk7bkmqg9mzwsxlm0y8m7s9qd9phr1q30qlx2qmdmz7c1mf"

["github.com/pkg/errors"]
  sumVersion = "v0.8.1"
  ["github.com/pkg/errors".fetch]
    type = "git"
    url = "https://github.com/pkg/errors"
    rev = "ba968bfe8b2f7e042a574c888954fccecfa385b4"
    sha256 = "0g5qcb4d4fd96midz0zdk8b9kz8xkzwfa8kr1cliqbg8sxsy5vd1"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/prometheus/client_golang"]
  sumVersion = "v1.2.1"
  ["github.com/prometheus/client_golang".fetch]
    type = "git"
    url = "https://github.com/prometheus/client_golang"
    rev = "55450579111f95e3722cb93dec62fe9e847d6130"
    sha256 = "0zs49psk23n9z8wrl02d5vib5wclpym8kaxcy6n5pk696i419065"

["github.com/prometheus/client_model"]
  sumVersion = "v0.0.0-20190812154241-14fe0d1b01d4"
  ["github.com/prometheus/client_model".fetch]
    type = "git"
    url = "https://github.com/prometheus/client_model"
    rev = "14fe0d1b01d4d5fc031dd4bec1823bd3ebbe8016"
    sha256 = "0zdmk6rbbx39cvfz0r59v2jg5sg9yd02b4pds5n5llgvivi99550"

["github.com/prometheus/common"]
  sumVersion = "v0.7.0"
  ["github.com/prometheus/common".fetch]
    type = "git"
    url = "https://github.com/prometheus/common"
    rev = "287d3e634a1e550c9e463dd7e5a75a422c614505"
    sha256 = "0a8yc0ppp50479sdhg9zbjnc4p7sqs6pdzvp27wzvccagbcy310c"

["github.com/prometheus/procfs"]
  sumVersion = "v0.0.5"
  ["github.com/prometheus/procfs".fetch]
    type = "git"
    url = "https://github.com/prometheus/procfs"
    rev = "499c85531f756d1129edd26485a5f73871eeb308"
    sha256 = "1nqn8ip9f4f6kqrvand4lxhcxrkk19dwf8s3nh336i9wr2jfhbwa"

["github.com/sirupsen/logrus"]
  sumVersion = "v1.4.2"
  ["github.com/sirupsen/logrus".fetch]
    type = "git"
    url = "https://github.com/sirupsen/logrus"
    rev = "839c75faf7f98a33d445d181f3018b5c3409a45e"
    sha256 = "087k2lxrr9p9dh68yw71d05h5g9p5v26zbwd6j7lghinjfaw334x"

["github.com/stretchr/objx"]
  sumVersion = "v0.1.1"
  ["github.com/stretchr/objx".fetch]
    type = "git"
    url = "https://github.com/stretchr/objx"
    rev = "477a77ecc69700c7cdeb1fa9e129548e1c1c393c"
    sha256 = "0iph0qmpyqg4kwv8jsx6a56a7hhqq8swrazv40ycxk9rzr0s8yls"

["github.com/stretchr/testify"]
  sumVersion = "v1.4.0"
  ["github.com/stretchr/testify".fetch]
    type = "git"
    url = "https://github.com/stretchr/testify"
    rev = "221dbe5ed46703ee255b1da0dec05086f5035f62"
    sha256 = "187i5g88sxfy4vxpm7dw1gwv29pa2qaq475lxrdh5livh69wqfjb"

["golang.org/x/crypto"]
  sumVersion = "v0.0.0-20190308221718-c2843e01d9a2"
  ["golang.org/x/crypto".fetch]
    type = "git"
    url = "https://go.googlesource.com/crypto"
    rev = "c2843e01d9a2bc60bb26ad24e09734fdc2d9ec58"
    sha256 = "01xgxbj5r79nmisdvpq48zfy8pzaaj90bn6ngd4nf33j9ar1dp8r"

["golang.org/x/lint"]
  sumVersion = "v0.0.0-20190409202823-959b441ac422"
  ["golang.org/x/lint".fetch]
    type = "git"
    url = "https://go.googlesource.com/lint"
    rev = "959b441ac422379a43da2230f62be024250818b0"
    sha256 = "1mgcv5f00pkzsbwnq2y7vqvd1b4lr5a3s47cphh2qv4indfk7pck"

["golang.org/x/net"]
  sumVersion = "v0.0.0-20190613194153-d28f0bde5980"
  ["golang.org/x/net".fetch]
    type = "git"
    url = "https://go.googlesource.com/net"
    rev = "d28f0bde5980168871434b95cfc858db9f2a7a99"
    sha256 = "18xj31h70m7xxb7gc86n9i21w6d7djbjz67zfaljm4jqskz6hxkf"

["golang.org/x/sync"]
  sumVersion = "v0.0.0-20181221193216-37e7f081c4d4"
  ["golang.org/x/sync".fetch]
    type = "git"
    url = "https://go.googlesource.com/sync"
    rev = "37e7f081c4d4c64e13b10787722085407fe5d15f"
    sha256 = "1bb0mw6ckb1k7z8v3iil2qlqwfj408fvvp8m1cik2b46p7snyjhm"

["golang.org/x/sys"]
  sumVersion = "v0.0.0-20191010194322-b09406accb47"
  ["golang.org/x/sys".fetch]
    type = "git"
    url = "https://go.googlesource.com/sys"
    rev = "b09406accb4736d857a32bf9444cd7edae2ffa79"
    sha256 = "00lbhsr2p3mi2n35mv3yy6lmgzjjav45yv9bmrxgyahbac5qnz5m"

["golang.org/x/text"]
  sumVersion = "v0.3.0"
  ["golang.org/x/text".fetch]
    type = "git"
    url = "https://go.googlesource.com/text"
    rev = "f21a4dfb5e38f5895301dc265a8def02365cc3d0"
    sha256 = "0r6x6zjzhr8ksqlpiwm5gdd7s209kwk5p4lw54xjvz10cs3qlq19"

["golang.org/x/tools"]
  sumVersion = "v0.0.0-20190311212946-11955173bddd"
  ["golang.org/x/tools".fetch]
    type = "git"
    url = "https://go.googlesource.com/tools"
    rev = "11955173bddd0ab0afcd688e6dc9c1b7c28fb546"
    sha256 = "0hlkai67w167wiyivkzd1fgqrnyxkb94l2c6kr51jwcscizfyfn3"

["gopkg.in/alecthomas/kingpin.v2"]
  sumVersion = "v2.2.6"
  ["gopkg.in/alecthomas/kingpin.v2".fetch]
    type = "git"
    url = "https://gopkg.in/alecthomas/kingpin.v2"
    rev = "947dcec5ba9c011838740e680966fd7087a71d0d"
    sha256 = "0mndnv3hdngr3bxp7yxfd47cas4prv98sqw534mx7vp38gd88n5r"

["gopkg.in/check.v1"]
  sumVersion = "v0.0.0-20161208181325-20d25e280405"
  ["gopkg.in/check.v1".fetch]
    type = "git"
    url = "https://gopkg.in/check.v1"
    rev = "20d25e2804050c1cd24a7eea1e7a6447dd0e74ec"
    sha256 = "0k1m83ji9l1a7ng8a7v40psbymxasmssbrrhpdv2wl4rhs0nc3np"

["gopkg.in/yaml.v2"]
  sumVersion = "v2.2.2"
  ["gopkg.in/yaml.v2".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v2"
    rev = "51d6538a90f86fe93ac480b35f37b2be17fef232"
    sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa"
